### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DABtester** [Highpoint2000/webserver-scanner#3]
I would like to ask the following feature:

At this moment when the autoscanner is running, the tuner is "locked" for users and cannot be used for manual tuning.
It would be great if the autoscanner can be started - but the tuner is still available for manual tuning.

When the scanner is started/running, a user can interrupt the scanner by using the tune +/- buttons, scroll up/down freq or manually entering the frequency.
The scanner will stop at this point, and the user can do his thing.
After X time (admin setting) when user activity stopped, the scanner will proceed scanning where it stopped previously.

Many thanks

**Comment by Highpoint2000** [comment]
Hello DABtester, 

 

thank you very much for contacting us and the suggestion. Maybe you haven't seen it yet, there is already a very similar function in the plugin. If you set autostart to "auto" in the configuration file, the autoscanner will work in the background when no one is connected. The principle is very similar because it stops when someone connects, then you can zap and it starts again after 10 seconds when the user leaves the server. I would not like to implement another function of this type because the code is already relatively complex. Please try this option, maybe it's enough? 

 

73, Highpoint

 

Von: DABtester ***@***.***> 
Gesendet: Mittwoch, 25. September 2024 18:57
An: Highpoint2000/webserver-scanner ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Highpoint2000/webserver-scanner] Feature request (Issue #3)

 

I would like to ask the following feature:

At this moment when the autoscanner is running, the tuner is "locked" for users and cannot be used for manual tuning.
It would be great if the autoscanner can be started - but the tuner is still available for manual tuning.

When the scanner is started/running, a user can interrupt the scanner by using the tune +/- buttons, scroll up/down freq or manually entering the frequency.
The scanner will stop at this point, and the user can do his thing.
After X time (admin setting) when user activity stopped, the scanner will proceed scanning where it stopped previously.

Many thanks

**Comment by DABtester** [comment]
That's perfect!

Will test it soon, thanks for your reply
